class_name Const

const MAX_SOURCES = 9
const MAX_ATTEMPTS = 3
const SCORE_PER_ATTEMPT := 100
const SCORE_FOR_HINT := 200
const NO_HINT_MULT_INCREMENT := 0.2
const DIFFICULTY_INCREASE_LEVEL := 5
const START_PHASE_SHIFT_FROM_LEVEL := 10
const MAX_LEVEL := 20